import pygame

# Konfiguracja czcionek
COLOR_WHITE = (255, 255, 255)
COLOR_BLACK = (0, 0, 0)
COLOR_GRAY = (100, 100, 100)
COLOR_RED = (200, 50, 50)
COLOR_TEXT_SELECTED = (50, 50, 50)
COLOR_TEXT_DESELECT = (100, 100, 100)

FONT_PATH = 'fonts\\upheavtt.ttf'
FONT_SIZE = 40
FONT_SIZE_LARGE = 60

# Wymiary okna
WINDOW_WIDTH = 1280
WINDOW_HEIGHT = 720

# Wielkość siatki samej podłogi
GRID_SIZE = 21

TOTAL_TILES_X = GRID_SIZE + 2
TOTAL_TILES_Y = GRID_SIZE + 2
TILE_WIDTH = WINDOW_WIDTH // TOTAL_TILES_X
TILE_HEIGHT = WINDOW_HEIGHT // TOTAL_TILES_Y

FLOOR_WIDTH_PX = TILE_WIDTH * GRID_SIZE
FLOOR_HEIGHT_PX = TILE_HEIGHT * GRID_SIZE

GRID_OFFSET_X = (WINDOW_WIDTH - FLOOR_WIDTH_PX) // 2
GRID_OFFSET_Y = (WINDOW_HEIGHT - FLOOR_HEIGHT_PX) // 2

GRID_BORDER_TOP = GRID_OFFSET_Y
GRID_BORDER_BOTTOM = GRID_OFFSET_Y + FLOOR_HEIGHT_PX
GRID_BORDER_LEFT = GRID_OFFSET_X
GRID_BORDER_RIGHT = GRID_OFFSET_X + FLOOR_WIDTH_PX

DOOR_WIDTH = TILE_WIDTH * 3
DOOR_HEIGHT = TILE_HEIGHT * 3